// source: iotics/api/search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_rpc_status_pb = require('../../google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
var iotics_api_common_pb = require('../../iotics/api/common_pb.js');
goog.object.extend(proto, iotics_api_common_pb);
var iotics_api_feed_pb = require('../../iotics/api/feed_pb.js');
goog.object.extend(proto, iotics_api_feed_pb);
var iotics_api_input_pb = require('../../iotics/api/input_pb.js');
goog.object.extend(proto, iotics_api_input_pb);
goog.exportSymbol('proto.iotics.api.AdvancedSearchRequest', null, global);
goog.exportSymbol('proto.iotics.api.AdvancedSearchRequest.Payload', null, global);
goog.exportSymbol('proto.iotics.api.DispatchSearchResponse', null, global);
goog.exportSymbol('proto.iotics.api.ResponseType', null, global);
goog.exportSymbol('proto.iotics.api.SearchRequest', null, global);
goog.exportSymbol('proto.iotics.api.SearchRequest.Payload', null, global);
goog.exportSymbol('proto.iotics.api.SearchRequest.Payload.Filter', null, global);
goog.exportSymbol('proto.iotics.api.SearchResponse', null, global);
goog.exportSymbol('proto.iotics.api.SearchResponse.FeedDetails', null, global);
goog.exportSymbol('proto.iotics.api.SearchResponse.InputDetails', null, global);
goog.exportSymbol('proto.iotics.api.SearchResponse.Payload', null, global);
goog.exportSymbol('proto.iotics.api.SearchResponse.TwinDetails', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.SearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchRequest.displayName = 'proto.iotics.api.SearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchRequest.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.SearchRequest.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchRequest.Payload.displayName = 'proto.iotics.api.SearchRequest.Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchRequest.Payload.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.iotics.api.SearchRequest.Payload.Filter.repeatedFields_, null);
};
goog.inherits(proto.iotics.api.SearchRequest.Payload.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchRequest.Payload.Filter.displayName = 'proto.iotics.api.SearchRequest.Payload.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.AdvancedSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.AdvancedSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.AdvancedSearchRequest.displayName = 'proto.iotics.api.AdvancedSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.AdvancedSearchRequest.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.AdvancedSearchRequest.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.AdvancedSearchRequest.Payload.displayName = 'proto.iotics.api.AdvancedSearchRequest.Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.SearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchResponse.displayName = 'proto.iotics.api.SearchResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchResponse.FeedDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.iotics.api.SearchResponse.FeedDetails.repeatedFields_, null);
};
goog.inherits(proto.iotics.api.SearchResponse.FeedDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchResponse.FeedDetails.displayName = 'proto.iotics.api.SearchResponse.FeedDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchResponse.InputDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.iotics.api.SearchResponse.InputDetails.repeatedFields_, null);
};
goog.inherits(proto.iotics.api.SearchResponse.InputDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchResponse.InputDetails.displayName = 'proto.iotics.api.SearchResponse.InputDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchResponse.TwinDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.iotics.api.SearchResponse.TwinDetails.repeatedFields_, null);
};
goog.inherits(proto.iotics.api.SearchResponse.TwinDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchResponse.TwinDetails.displayName = 'proto.iotics.api.SearchResponse.TwinDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.SearchResponse.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.iotics.api.SearchResponse.Payload.repeatedFields_, null);
};
goog.inherits(proto.iotics.api.SearchResponse.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.SearchResponse.Payload.displayName = 'proto.iotics.api.SearchResponse.Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotics.api.DispatchSearchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iotics.api.DispatchSearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.iotics.api.DispatchSearchResponse.displayName = 'proto.iotics.api.DispatchSearchResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    headers: (f = msg.getHeaders()) && iotics_api_common_pb.Headers.toObject(includeInstance, f),
    scope: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lang: (f = msg.getLang()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && proto.iotics.api.SearchRequest.Payload.toObject(includeInstance, f),
    range: (f = msg.getRange()) && iotics_api_common_pb.Range.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchRequest}
 */
proto.iotics.api.SearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchRequest;
  return proto.iotics.api.SearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchRequest}
 */
proto.iotics.api.SearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_common_pb.Headers;
      reader.readMessage(value,iotics_api_common_pb.Headers.deserializeBinaryFromReader);
      msg.setHeaders(value);
      break;
    case 2:
      var value = /** @type {!proto.iotics.api.Scope} */ (reader.readEnum());
      msg.setScope(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setLang(value);
      break;
    case 6:
      var value = new proto.iotics.api.SearchRequest.Payload;
      reader.readMessage(value,proto.iotics.api.SearchRequest.Payload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 20:
      var value = new iotics_api_common_pb.Range;
      reader.readMessage(value,iotics_api_common_pb.Range.deserializeBinaryFromReader);
      msg.setRange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaders();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_common_pb.Headers.serializeBinaryToWriter
    );
  }
  f = message.getScope();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLang();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.iotics.api.SearchRequest.Payload.serializeBinaryToWriter
    );
  }
  f = message.getRange();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      iotics_api_common_pb.Range.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchRequest.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchRequest.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchRequest.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    responsetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    expirytimeout: (f = msg.getExpirytimeout()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    filter: (f = msg.getFilter()) && proto.iotics.api.SearchRequest.Payload.Filter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchRequest.Payload}
 */
proto.iotics.api.SearchRequest.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchRequest.Payload;
  return proto.iotics.api.SearchRequest.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchRequest.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchRequest.Payload}
 */
proto.iotics.api.SearchRequest.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.iotics.api.ResponseType} */ (reader.readEnum());
      msg.setResponsetype(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirytimeout(value);
      break;
    case 3:
      var value = new proto.iotics.api.SearchRequest.Payload.Filter;
      reader.readMessage(value,proto.iotics.api.SearchRequest.Payload.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchRequest.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchRequest.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchRequest.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponsetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getExpirytimeout();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.iotics.api.SearchRequest.Payload.Filter.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.iotics.api.SearchRequest.Payload.Filter.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchRequest.Payload.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchRequest.Payload.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.Payload.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: (f = msg.getText()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    location: (f = msg.getLocation()) && iotics_api_common_pb.GeoCircle.toObject(includeInstance, f),
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    iotics_api_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter}
 */
proto.iotics.api.SearchRequest.Payload.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchRequest.Payload.Filter;
  return proto.iotics.api.SearchRequest.Payload.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchRequest.Payload.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter}
 */
proto.iotics.api.SearchRequest.Payload.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 2:
      var value = new iotics_api_common_pb.GeoCircle;
      reader.readMessage(value,iotics_api_common_pb.GeoCircle.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 3:
      var value = new iotics_api_common_pb.Property;
      reader.readMessage(value,iotics_api_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchRequest.Payload.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchRequest.Payload.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchRequest.Payload.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      iotics_api_common_pb.GeoCircle.serializeBinaryToWriter
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      iotics_api_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue text = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.getText = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
*/
proto.iotics.api.SearchRequest.Payload.Filter.prototype.setText = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.clearText = function() {
  return this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.hasText = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GeoCircle location = 2;
 * @return {?proto.iotics.api.GeoCircle}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.getLocation = function() {
  return /** @type{?proto.iotics.api.GeoCircle} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.GeoCircle, 2));
};


/**
 * @param {?proto.iotics.api.GeoCircle|undefined} value
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
*/
proto.iotics.api.SearchRequest.Payload.Filter.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Property properties = 3;
 * @return {!Array<!proto.iotics.api.Property>}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.iotics.api.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, iotics_api_common_pb.Property, 3));
};


/**
 * @param {!Array<!proto.iotics.api.Property>} value
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
*/
proto.iotics.api.SearchRequest.Payload.Filter.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.iotics.api.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.Property}
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.iotics.api.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchRequest.Payload.Filter} returns this
 */
proto.iotics.api.SearchRequest.Payload.Filter.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};


/**
 * optional ResponseType responseType = 1;
 * @return {!proto.iotics.api.ResponseType}
 */
proto.iotics.api.SearchRequest.Payload.prototype.getResponsetype = function() {
  return /** @type {!proto.iotics.api.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.iotics.api.ResponseType} value
 * @return {!proto.iotics.api.SearchRequest.Payload} returns this
 */
proto.iotics.api.SearchRequest.Payload.prototype.setResponsetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp expiryTimeout = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.iotics.api.SearchRequest.Payload.prototype.getExpirytimeout = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.iotics.api.SearchRequest.Payload} returns this
*/
proto.iotics.api.SearchRequest.Payload.prototype.setExpirytimeout = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest.Payload} returns this
 */
proto.iotics.api.SearchRequest.Payload.prototype.clearExpirytimeout = function() {
  return this.setExpirytimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.Payload.prototype.hasExpirytimeout = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Filter filter = 3;
 * @return {?proto.iotics.api.SearchRequest.Payload.Filter}
 */
proto.iotics.api.SearchRequest.Payload.prototype.getFilter = function() {
  return /** @type{?proto.iotics.api.SearchRequest.Payload.Filter} */ (
    jspb.Message.getWrapperField(this, proto.iotics.api.SearchRequest.Payload.Filter, 3));
};


/**
 * @param {?proto.iotics.api.SearchRequest.Payload.Filter|undefined} value
 * @return {!proto.iotics.api.SearchRequest.Payload} returns this
*/
proto.iotics.api.SearchRequest.Payload.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest.Payload} returns this
 */
proto.iotics.api.SearchRequest.Payload.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.Payload.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Headers headers = 1;
 * @return {?proto.iotics.api.Headers}
 */
proto.iotics.api.SearchRequest.prototype.getHeaders = function() {
  return /** @type{?proto.iotics.api.Headers} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.Headers, 1));
};


/**
 * @param {?proto.iotics.api.Headers|undefined} value
 * @return {!proto.iotics.api.SearchRequest} returns this
*/
proto.iotics.api.SearchRequest.prototype.setHeaders = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest} returns this
 */
proto.iotics.api.SearchRequest.prototype.clearHeaders = function() {
  return this.setHeaders(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.prototype.hasHeaders = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Scope scope = 2;
 * @return {!proto.iotics.api.Scope}
 */
proto.iotics.api.SearchRequest.prototype.getScope = function() {
  return /** @type {!proto.iotics.api.Scope} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.iotics.api.Scope} value
 * @return {!proto.iotics.api.SearchRequest} returns this
 */
proto.iotics.api.SearchRequest.prototype.setScope = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue lang = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.iotics.api.SearchRequest.prototype.getLang = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.iotics.api.SearchRequest} returns this
*/
proto.iotics.api.SearchRequest.prototype.setLang = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest} returns this
 */
proto.iotics.api.SearchRequest.prototype.clearLang = function() {
  return this.setLang(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.prototype.hasLang = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Payload payload = 6;
 * @return {?proto.iotics.api.SearchRequest.Payload}
 */
proto.iotics.api.SearchRequest.prototype.getPayload = function() {
  return /** @type{?proto.iotics.api.SearchRequest.Payload} */ (
    jspb.Message.getWrapperField(this, proto.iotics.api.SearchRequest.Payload, 6));
};


/**
 * @param {?proto.iotics.api.SearchRequest.Payload|undefined} value
 * @return {!proto.iotics.api.SearchRequest} returns this
*/
proto.iotics.api.SearchRequest.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest} returns this
 */
proto.iotics.api.SearchRequest.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Range range = 20;
 * @return {?proto.iotics.api.Range}
 */
proto.iotics.api.SearchRequest.prototype.getRange = function() {
  return /** @type{?proto.iotics.api.Range} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.Range, 20));
};


/**
 * @param {?proto.iotics.api.Range|undefined} value
 * @return {!proto.iotics.api.SearchRequest} returns this
*/
proto.iotics.api.SearchRequest.prototype.setRange = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchRequest} returns this
 */
proto.iotics.api.SearchRequest.prototype.clearRange = function() {
  return this.setRange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchRequest.prototype.hasRange = function() {
  return jspb.Message.getField(this, 20) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.AdvancedSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.AdvancedSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.AdvancedSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    headers: (f = msg.getHeaders()) && iotics_api_common_pb.Headers.toObject(includeInstance, f),
    scope: jspb.Message.getFieldWithDefault(msg, 2, 0),
    payload: (f = msg.getPayload()) && proto.iotics.api.AdvancedSearchRequest.Payload.toObject(includeInstance, f),
    range: (f = msg.getRange()) && iotics_api_common_pb.Range.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.AdvancedSearchRequest}
 */
proto.iotics.api.AdvancedSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.AdvancedSearchRequest;
  return proto.iotics.api.AdvancedSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.AdvancedSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.AdvancedSearchRequest}
 */
proto.iotics.api.AdvancedSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_common_pb.Headers;
      reader.readMessage(value,iotics_api_common_pb.Headers.deserializeBinaryFromReader);
      msg.setHeaders(value);
      break;
    case 2:
      var value = /** @type {!proto.iotics.api.Scope} */ (reader.readEnum());
      msg.setScope(value);
      break;
    case 3:
      var value = new proto.iotics.api.AdvancedSearchRequest.Payload;
      reader.readMessage(value,proto.iotics.api.AdvancedSearchRequest.Payload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 20:
      var value = new iotics_api_common_pb.Range;
      reader.readMessage(value,iotics_api_common_pb.Range.deserializeBinaryFromReader);
      msg.setRange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.AdvancedSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.AdvancedSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.AdvancedSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaders();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_common_pb.Headers.serializeBinaryToWriter
    );
  }
  f = message.getScope();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.iotics.api.AdvancedSearchRequest.Payload.serializeBinaryToWriter
    );
  }
  f = message.getRange();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      iotics_api_common_pb.Range.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.AdvancedSearchRequest.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.AdvancedSearchRequest.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.AdvancedSearchRequest.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    responsetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    filter: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.AdvancedSearchRequest.Payload}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.AdvancedSearchRequest.Payload;
  return proto.iotics.api.AdvancedSearchRequest.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.AdvancedSearchRequest.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.AdvancedSearchRequest.Payload}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.iotics.api.ResponseType} */ (reader.readEnum());
      msg.setResponsetype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.AdvancedSearchRequest.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.AdvancedSearchRequest.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.AdvancedSearchRequest.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponsetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getFilter();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ResponseType responseType = 1;
 * @return {!proto.iotics.api.ResponseType}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.getResponsetype = function() {
  return /** @type {!proto.iotics.api.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.iotics.api.ResponseType} value
 * @return {!proto.iotics.api.AdvancedSearchRequest.Payload} returns this
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.setResponsetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string filter = 2;
 * @return {string}
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.getFilter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.iotics.api.AdvancedSearchRequest.Payload} returns this
 */
proto.iotics.api.AdvancedSearchRequest.Payload.prototype.setFilter = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Headers headers = 1;
 * @return {?proto.iotics.api.Headers}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.getHeaders = function() {
  return /** @type{?proto.iotics.api.Headers} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.Headers, 1));
};


/**
 * @param {?proto.iotics.api.Headers|undefined} value
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
*/
proto.iotics.api.AdvancedSearchRequest.prototype.setHeaders = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
 */
proto.iotics.api.AdvancedSearchRequest.prototype.clearHeaders = function() {
  return this.setHeaders(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.hasHeaders = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Scope scope = 2;
 * @return {!proto.iotics.api.Scope}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.getScope = function() {
  return /** @type {!proto.iotics.api.Scope} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.iotics.api.Scope} value
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
 */
proto.iotics.api.AdvancedSearchRequest.prototype.setScope = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Payload payload = 3;
 * @return {?proto.iotics.api.AdvancedSearchRequest.Payload}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.getPayload = function() {
  return /** @type{?proto.iotics.api.AdvancedSearchRequest.Payload} */ (
    jspb.Message.getWrapperField(this, proto.iotics.api.AdvancedSearchRequest.Payload, 3));
};


/**
 * @param {?proto.iotics.api.AdvancedSearchRequest.Payload|undefined} value
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
*/
proto.iotics.api.AdvancedSearchRequest.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
 */
proto.iotics.api.AdvancedSearchRequest.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Range range = 20;
 * @return {?proto.iotics.api.Range}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.getRange = function() {
  return /** @type{?proto.iotics.api.Range} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.Range, 20));
};


/**
 * @param {?proto.iotics.api.Range|undefined} value
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
*/
proto.iotics.api.AdvancedSearchRequest.prototype.setRange = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.AdvancedSearchRequest} returns this
 */
proto.iotics.api.AdvancedSearchRequest.prototype.clearRange = function() {
  return this.setRange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.AdvancedSearchRequest.prototype.hasRange = function() {
  return jspb.Message.getField(this, 20) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    headers: (f = msg.getHeaders()) && iotics_api_common_pb.Headers.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && proto.iotics.api.SearchResponse.Payload.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchResponse}
 */
proto.iotics.api.SearchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchResponse;
  return proto.iotics.api.SearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchResponse}
 */
proto.iotics.api.SearchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_common_pb.Headers;
      reader.readMessage(value,iotics_api_common_pb.Headers.deserializeBinaryFromReader);
      msg.setHeaders(value);
      break;
    case 2:
      var value = new proto.iotics.api.SearchResponse.Payload;
      reader.readMessage(value,proto.iotics.api.SearchResponse.Payload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaders();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_common_pb.Headers.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.iotics.api.SearchResponse.Payload.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.iotics.api.SearchResponse.FeedDetails.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchResponse.FeedDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchResponse.FeedDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.FeedDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    feedid: (f = msg.getFeedid()) && iotics_api_feed_pb.FeedID.toObject(includeInstance, f),
    storelast: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    iotics_api_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchResponse.FeedDetails}
 */
proto.iotics.api.SearchResponse.FeedDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchResponse.FeedDetails;
  return proto.iotics.api.SearchResponse.FeedDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchResponse.FeedDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchResponse.FeedDetails}
 */
proto.iotics.api.SearchResponse.FeedDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_feed_pb.FeedID;
      reader.readMessage(value,iotics_api_feed_pb.FeedID.deserializeBinaryFromReader);
      msg.setFeedid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStorelast(value);
      break;
    case 4:
      var value = new iotics_api_common_pb.Property;
      reader.readMessage(value,iotics_api_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchResponse.FeedDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchResponse.FeedDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.FeedDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFeedid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_feed_pb.FeedID.serializeBinaryToWriter
    );
  }
  f = message.getStorelast();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      iotics_api_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional FeedID feedId = 1;
 * @return {?proto.iotics.api.FeedID}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.getFeedid = function() {
  return /** @type{?proto.iotics.api.FeedID} */ (
    jspb.Message.getWrapperField(this, iotics_api_feed_pb.FeedID, 1));
};


/**
 * @param {?proto.iotics.api.FeedID|undefined} value
 * @return {!proto.iotics.api.SearchResponse.FeedDetails} returns this
*/
proto.iotics.api.SearchResponse.FeedDetails.prototype.setFeedid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.FeedDetails} returns this
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.clearFeedid = function() {
  return this.setFeedid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.hasFeedid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool storeLast = 3;
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.getStorelast = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.iotics.api.SearchResponse.FeedDetails} returns this
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.setStorelast = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated Property properties = 4;
 * @return {!Array<!proto.iotics.api.Property>}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.iotics.api.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, iotics_api_common_pb.Property, 4));
};


/**
 * @param {!Array<!proto.iotics.api.Property>} value
 * @return {!proto.iotics.api.SearchResponse.FeedDetails} returns this
*/
proto.iotics.api.SearchResponse.FeedDetails.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.iotics.api.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.Property}
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.iotics.api.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.FeedDetails} returns this
 */
proto.iotics.api.SearchResponse.FeedDetails.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.iotics.api.SearchResponse.InputDetails.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchResponse.InputDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchResponse.InputDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.InputDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    inputid: (f = msg.getInputid()) && iotics_api_input_pb.InputID.toObject(includeInstance, f),
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    iotics_api_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchResponse.InputDetails}
 */
proto.iotics.api.SearchResponse.InputDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchResponse.InputDetails;
  return proto.iotics.api.SearchResponse.InputDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchResponse.InputDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchResponse.InputDetails}
 */
proto.iotics.api.SearchResponse.InputDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_input_pb.InputID;
      reader.readMessage(value,iotics_api_input_pb.InputID.deserializeBinaryFromReader);
      msg.setInputid(value);
      break;
    case 4:
      var value = new iotics_api_common_pb.Property;
      reader.readMessage(value,iotics_api_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchResponse.InputDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchResponse.InputDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.InputDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInputid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_input_pb.InputID.serializeBinaryToWriter
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      iotics_api_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional InputID inputId = 1;
 * @return {?proto.iotics.api.InputID}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.getInputid = function() {
  return /** @type{?proto.iotics.api.InputID} */ (
    jspb.Message.getWrapperField(this, iotics_api_input_pb.InputID, 1));
};


/**
 * @param {?proto.iotics.api.InputID|undefined} value
 * @return {!proto.iotics.api.SearchResponse.InputDetails} returns this
*/
proto.iotics.api.SearchResponse.InputDetails.prototype.setInputid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.InputDetails} returns this
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.clearInputid = function() {
  return this.setInputid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.hasInputid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Property properties = 4;
 * @return {!Array<!proto.iotics.api.Property>}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.iotics.api.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, iotics_api_common_pb.Property, 4));
};


/**
 * @param {!Array<!proto.iotics.api.Property>} value
 * @return {!proto.iotics.api.SearchResponse.InputDetails} returns this
*/
proto.iotics.api.SearchResponse.InputDetails.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.iotics.api.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.Property}
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.iotics.api.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.InputDetails} returns this
 */
proto.iotics.api.SearchResponse.InputDetails.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.iotics.api.SearchResponse.TwinDetails.repeatedFields_ = [5,10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchResponse.TwinDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchResponse.TwinDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.TwinDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    twinid: (f = msg.getTwinid()) && iotics_api_common_pb.TwinID.toObject(includeInstance, f),
    location: (f = msg.getLocation()) && iotics_api_common_pb.GeoLocation.toObject(includeInstance, f),
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    iotics_api_common_pb.Property.toObject, includeInstance),
    feedsList: jspb.Message.toObjectList(msg.getFeedsList(),
    proto.iotics.api.SearchResponse.FeedDetails.toObject, includeInstance),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.iotics.api.SearchResponse.InputDetails.toObject, includeInstance),
    updatedat: (f = msg.getUpdatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails}
 */
proto.iotics.api.SearchResponse.TwinDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchResponse.TwinDetails;
  return proto.iotics.api.SearchResponse.TwinDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchResponse.TwinDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails}
 */
proto.iotics.api.SearchResponse.TwinDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new iotics_api_common_pb.TwinID;
      reader.readMessage(value,iotics_api_common_pb.TwinID.deserializeBinaryFromReader);
      msg.setTwinid(value);
      break;
    case 2:
      var value = new iotics_api_common_pb.GeoLocation;
      reader.readMessage(value,iotics_api_common_pb.GeoLocation.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 5:
      var value = new iotics_api_common_pb.Property;
      reader.readMessage(value,iotics_api_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    case 10:
      var value = new proto.iotics.api.SearchResponse.FeedDetails;
      reader.readMessage(value,proto.iotics.api.SearchResponse.FeedDetails.deserializeBinaryFromReader);
      msg.addFeeds(value);
      break;
    case 11:
      var value = new proto.iotics.api.SearchResponse.InputDetails;
      reader.readMessage(value,proto.iotics.api.SearchResponse.InputDetails.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 13:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchResponse.TwinDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchResponse.TwinDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.TwinDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTwinid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      iotics_api_common_pb.TwinID.serializeBinaryToWriter
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      iotics_api_common_pb.GeoLocation.serializeBinaryToWriter
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      iotics_api_common_pb.Property.serializeBinaryToWriter
    );
  }
  f = message.getFeedsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.iotics.api.SearchResponse.FeedDetails.serializeBinaryToWriter
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.iotics.api.SearchResponse.InputDetails.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedat();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional TwinID twinId = 1;
 * @return {?proto.iotics.api.TwinID}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getTwinid = function() {
  return /** @type{?proto.iotics.api.TwinID} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.TwinID, 1));
};


/**
 * @param {?proto.iotics.api.TwinID|undefined} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setTwinid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearTwinid = function() {
  return this.setTwinid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.hasTwinid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GeoLocation location = 2;
 * @return {?proto.iotics.api.GeoLocation}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getLocation = function() {
  return /** @type{?proto.iotics.api.GeoLocation} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.GeoLocation, 2));
};


/**
 * @param {?proto.iotics.api.GeoLocation|undefined} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Property properties = 5;
 * @return {!Array<!proto.iotics.api.Property>}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.iotics.api.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, iotics_api_common_pb.Property, 5));
};


/**
 * @param {!Array<!proto.iotics.api.Property>} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.iotics.api.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.Property}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.iotics.api.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};


/**
 * repeated FeedDetails feeds = 10;
 * @return {!Array<!proto.iotics.api.SearchResponse.FeedDetails>}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getFeedsList = function() {
  return /** @type{!Array<!proto.iotics.api.SearchResponse.FeedDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.iotics.api.SearchResponse.FeedDetails, 10));
};


/**
 * @param {!Array<!proto.iotics.api.SearchResponse.FeedDetails>} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setFeedsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.iotics.api.SearchResponse.FeedDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.SearchResponse.FeedDetails}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.addFeeds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.iotics.api.SearchResponse.FeedDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearFeedsList = function() {
  return this.setFeedsList([]);
};


/**
 * repeated InputDetails inputs = 11;
 * @return {!Array<!proto.iotics.api.SearchResponse.InputDetails>}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.iotics.api.SearchResponse.InputDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.iotics.api.SearchResponse.InputDetails, 11));
};


/**
 * @param {!Array<!proto.iotics.api.SearchResponse.InputDetails>} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setInputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.iotics.api.SearchResponse.InputDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.SearchResponse.InputDetails}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.iotics.api.SearchResponse.InputDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearInputsList = function() {
  return this.setInputsList([]);
};


/**
 * optional google.protobuf.Timestamp updatedAt = 13;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.getUpdatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 13));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
*/
proto.iotics.api.SearchResponse.TwinDetails.prototype.setUpdatedat = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.TwinDetails} returns this
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.clearUpdatedat = function() {
  return this.setUpdatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.TwinDetails.prototype.hasUpdatedat = function() {
  return jspb.Message.getField(this, 13) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.iotics.api.SearchResponse.Payload.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.SearchResponse.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.SearchResponse.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.SearchResponse.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    responsetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
    hostid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    twinsList: jspb.Message.toObjectList(msg.getTwinsList(),
    proto.iotics.api.SearchResponse.TwinDetails.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.SearchResponse.Payload}
 */
proto.iotics.api.SearchResponse.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.SearchResponse.Payload;
  return proto.iotics.api.SearchResponse.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.SearchResponse.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.SearchResponse.Payload}
 */
proto.iotics.api.SearchResponse.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.iotics.api.ResponseType} */ (reader.readEnum());
      msg.setResponsetype(value);
      break;
    case 2:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHostid(value);
      break;
    case 10:
      var value = new proto.iotics.api.SearchResponse.TwinDetails;
      reader.readMessage(value,proto.iotics.api.SearchResponse.TwinDetails.deserializeBinaryFromReader);
      msg.addTwins(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.SearchResponse.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.SearchResponse.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.SearchResponse.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.SearchResponse.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponsetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getHostid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTwinsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.iotics.api.SearchResponse.TwinDetails.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseType responseType = 1;
 * @return {!proto.iotics.api.ResponseType}
 */
proto.iotics.api.SearchResponse.Payload.prototype.getResponsetype = function() {
  return /** @type {!proto.iotics.api.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.iotics.api.ResponseType} value
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
 */
proto.iotics.api.SearchResponse.Payload.prototype.setResponsetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional google.rpc.Status status = 2;
 * @return {?proto.google.rpc.Status}
 */
proto.iotics.api.SearchResponse.Payload.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 2));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
*/
proto.iotics.api.SearchResponse.Payload.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
 */
proto.iotics.api.SearchResponse.Payload.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.Payload.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string hostId = 3;
 * @return {string}
 */
proto.iotics.api.SearchResponse.Payload.prototype.getHostid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
 */
proto.iotics.api.SearchResponse.Payload.prototype.setHostid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated TwinDetails twins = 10;
 * @return {!Array<!proto.iotics.api.SearchResponse.TwinDetails>}
 */
proto.iotics.api.SearchResponse.Payload.prototype.getTwinsList = function() {
  return /** @type{!Array<!proto.iotics.api.SearchResponse.TwinDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.iotics.api.SearchResponse.TwinDetails, 10));
};


/**
 * @param {!Array<!proto.iotics.api.SearchResponse.TwinDetails>} value
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
*/
proto.iotics.api.SearchResponse.Payload.prototype.setTwinsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.iotics.api.SearchResponse.TwinDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.iotics.api.SearchResponse.TwinDetails}
 */
proto.iotics.api.SearchResponse.Payload.prototype.addTwins = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.iotics.api.SearchResponse.TwinDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.iotics.api.SearchResponse.Payload} returns this
 */
proto.iotics.api.SearchResponse.Payload.prototype.clearTwinsList = function() {
  return this.setTwinsList([]);
};


/**
 * optional Headers headers = 1;
 * @return {?proto.iotics.api.Headers}
 */
proto.iotics.api.SearchResponse.prototype.getHeaders = function() {
  return /** @type{?proto.iotics.api.Headers} */ (
    jspb.Message.getWrapperField(this, iotics_api_common_pb.Headers, 1));
};


/**
 * @param {?proto.iotics.api.Headers|undefined} value
 * @return {!proto.iotics.api.SearchResponse} returns this
*/
proto.iotics.api.SearchResponse.prototype.setHeaders = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse} returns this
 */
proto.iotics.api.SearchResponse.prototype.clearHeaders = function() {
  return this.setHeaders(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.prototype.hasHeaders = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Payload payload = 2;
 * @return {?proto.iotics.api.SearchResponse.Payload}
 */
proto.iotics.api.SearchResponse.prototype.getPayload = function() {
  return /** @type{?proto.iotics.api.SearchResponse.Payload} */ (
    jspb.Message.getWrapperField(this, proto.iotics.api.SearchResponse.Payload, 2));
};


/**
 * @param {?proto.iotics.api.SearchResponse.Payload|undefined} value
 * @return {!proto.iotics.api.SearchResponse} returns this
*/
proto.iotics.api.SearchResponse.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.iotics.api.SearchResponse} returns this
 */
proto.iotics.api.SearchResponse.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.iotics.api.SearchResponse.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotics.api.DispatchSearchResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.iotics.api.DispatchSearchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotics.api.DispatchSearchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.DispatchSearchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotics.api.DispatchSearchResponse}
 */
proto.iotics.api.DispatchSearchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotics.api.DispatchSearchResponse;
  return proto.iotics.api.DispatchSearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotics.api.DispatchSearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotics.api.DispatchSearchResponse}
 */
proto.iotics.api.DispatchSearchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotics.api.DispatchSearchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotics.api.DispatchSearchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotics.api.DispatchSearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotics.api.DispatchSearchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.iotics.api.ResponseType = {
  FULL: 0,
  LOCATED: 1,
  MINIMAL: 2
};

goog.object.extend(exports, proto.iotics.api);
