name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "'${{ env.TAG }}'"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          registry-url: https://registry.npmjs.org/
      - run: make deps-node publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: iotics-grpc-client-v*.tgz
